import { Post } from '#features/auth/types';
import image1 from './image/image 9.png';

export const allPosts: Post[] = [
  {
    id: 0,
    image: image1,
    rating: 1,
    desc: 'Practical Guide to MongoDB: Architecting, Developing, and Administering MongoDB begins with a short introduction to the basics of NoSQL databases and then introduces readers to MongoDB - the leading document based NoSQL database, acquainting them step-by-step with all aspects of MongoDB.Practical Gu...',
    subtitle:
      'Astronauts Kayla Barron and Raja Chari floated out of the International Space Station airlock for a spacewalk Tuesday, installing brackets and struts to support new solar arrays to upgrade the research lab’s power system on the same day that crewmate Mark Vande Hei marked his 341st day in orbit, a U.S. record for a single spaceflight.',
    title: 'Practical MongoDB',
    authors: 'Shakuntala Gupta Edward, Navin Sabharwal',
    price: '$44.15',
    publisher: 'Apress',
    year: 2015,
    pages: 272,
    language: 'English',
    format: 'Paper book / ebook (PDF)',
    isbn10: 123252,
    isbn13: 2331542,
    error: 0,
    url: 'we',
  },
  {
    id: 1,
    image: image1,
    rating: 2,
    desc: 'Practical Guide to MongoDB: Architecting, Developing, and Administering MongoDB begins with a short introduction to the basics of NoSQL databases and then introduces readers to MongoDB - the leading document based NoSQL database, acquainting them step-by-step with all aspects of MongoDB.Practical Gu...',
    subtitle:
      'Astronauts Kayla Barron and Raja Chari floated out of the International Space Station airlock for a spacewalk Tuesday, installing brackets and struts to support new solar arrays to upgrade the research lab’s power system on the same day that crewmate Mark Vande Hei marked his 341st day in orbit, a U.S. record for a single spaceflight.',
    title: 'Practical MongoDB',
    authors: 'Shakuntala Gupta Edward, Navin Sabharwal',
    price: '$44.15',
    publisher: 'Apress',
    year: 2015,
    pages: 272,
    language: 'English',
    format: 'Paper book / ebook (PDF)',
    isbn10: 123252,
    isbn13: 2331542,
    error: 0,
    url: 'we',
  },
  {
    id: 2,
    image: image1,
    rating: 5,
    desc: 'Practical Guide to MongoDB: Architecting, Developing, and Administering MongoDB begins with a short introduction to the basics of NoSQL databases and then introduces readers to MongoDB - the leading document based NoSQL database, acquainting them step-by-step with all aspects of MongoDB.Practical Gu...',
    subtitle:
      'Astronauts Kayla Barron and Raja Chari floated out of the International Space Station airlock for a spacewalk Tuesday, installing brackets and struts to support new solar arrays to upgrade the research lab’s power system on the same day that crewmate Mark Vande Hei marked his 341st day in orbit, a U.S. record for a single spaceflight.',
    title: 'Practical MongoDB',
    authors: 'Shakuntala Gupta Edward, Navin Sabharwal',
    price: '$44.15',
    publisher: 'Apress',
    year: 2015,
    pages: 272,
    language: 'English',
    format: 'Paper book / ebook (PDF)',
    isbn10: 123252,
    isbn13: 2331542,
    error: 0,
    url: 'we',
  },
  {
    id: 3,
    image: image1,
    rating: 2,
    desc: 'Practical Guide to MongoDB: Architecting, Developing, and Administering MongoDB begins with a short introduction to the basics of NoSQL databases and then introduces readers to MongoDB - the leading document based NoSQL database, acquainting them step-by-step with all aspects of MongoDB.Practical Gu...',
    subtitle:
      'Astronauts Kayla Barron and Raja Chari floated out of the International Space Station airlock for a spacewalk Tuesday, installing brackets and struts to support new solar arrays to upgrade the research lab’s power system on the same day that crewmate Mark Vande Hei marked his 341st day in orbit, a U.S. record for a single spaceflight.',
    title: 'Practical MongoDB',
    authors: 'Shakuntala Gupta Edward, Navin Sabharwal',
    price: '$44.15',
    publisher: 'Apress',
    year: 2015,
    pages: 272,
    language: 'English',
    format: 'Paper book / ebook (PDF)',
    isbn10: 123252,
    isbn13: 2331542,
    error: 0,
    url: 'we',
  },
  {
    id: 4,
    image: image1,
    rating: 4,
    desc: 'Practical Guide to MongoDB: Architecting, Developing, and Administering MongoDB begins with a short introduction to the basics of NoSQL databases and then introduces readers to MongoDB - the leading document based NoSQL database, acquainting them step-by-step with all aspects of MongoDB.Practical Gu...',
    subtitle:
      'Astronauts Kayla Barron and Raja Chari floated out of the International Space Station airlock for a spacewalk Tuesday, installing brackets and struts to support new solar arrays to upgrade the research lab’s power system on the same day that crewmate Mark Vande Hei marked his 341st day in orbit, a U.S. record for a single spaceflight.',
    title: 'Practical MongoDB',
    authors: 'Shakuntala Gupta Edward, Navin Sabharwal',
    price: '$44.15',
    publisher: 'Apress',
    year: 2015,
    pages: 272,
    language: 'English',
    format: 'Paper book / ebook (PDF)',
    isbn10: 123252,
    isbn13: 2331542,
    error: 0,
    url: 'we',
  },
  {
    id: 5,
    image: image1,
    rating: 2,
    desc: 'Practical Guide to MongoDB: Architecting, Developing, and Administering MongoDB begins with a short introduction to the basics of NoSQL databases and then introduces readers to MongoDB - the leading document based NoSQL database, acquainting them step-by-step with all aspects of MongoDB.Practical Gu...',
    subtitle:
      'Astronauts Kayla Barron and Raja Chari floated out of the International Space Station airlock for a spacewalk Tuesday, installing brackets and struts to support new solar arrays to upgrade the research lab’s power system on the same day that crewmate Mark Vande Hei marked his 341st day in orbit, a U.S. record for a single spaceflight.',
    title: 'Practical MongoDB',
    authors: 'Shakuntala Gupta Edward, Navin Sabharwal',
    price: '$44.15',
    publisher: 'Apress',
    year: 2015,
    pages: 272,
    language: 'English',
    format: 'Paper book / ebook (PDF)',
    isbn10: 123252,
    isbn13: 2331542,
    error: 0,
    url: 'we',
  },
  {
    id: 6,
    image: image1,
    rating: 1,
    desc: 'Practical Guide to MongoDB: Architecting, Developing, and Administering MongoDB begins with a short introduction to the basics of NoSQL databases and then introduces readers to MongoDB - the leading document based NoSQL database, acquainting them step-by-step with all aspects of MongoDB.Practical Gu...',
    subtitle:
      'Astronauts Kayla Barron and Raja Chari floated out of the International Space Station airlock for a spacewalk Tuesday, installing brackets and struts to support new solar arrays to upgrade the research lab’s power system on the same day that crewmate Mark Vande Hei marked his 341st day in orbit, a U.S. record for a single spaceflight.',
    title: 'Practical MongoDB',
    authors: 'Shakuntala Gupta Edward, Navin Sabharwal',
    price: '$44.15',
    publisher: 'Apress',
    year: 2015,
    pages: 272,
    language: 'English',
    format: 'Paper book / ebook (PDF)',
    isbn10: 123252,
    isbn13: 2331542,
    error: 0,
    url: 'we',
  },
  {
    id: 7,
    image: image1,
    rating: 3,
    desc: 'Practical Guide to MongoDB: Architecting, Developing, and Administering MongoDB begins with a short introduction to the basics of NoSQL databases and then introduces readers to MongoDB - the leading document based NoSQL database, acquainting them step-by-step with all aspects of MongoDB.Practical Gu...',
    subtitle:
      'Astronauts Kayla Barron and Raja Chari floated out of the International Space Station airlock for a spacewalk Tuesday, installing brackets and struts to support new solar arrays to upgrade the research lab’s power system on the same day that crewmate Mark Vande Hei marked his 341st day in orbit, a U.S. record for a single spaceflight.',
    title: 'Practical MongoDB',
    authors: 'Shakuntala Gupta Edward, Navin Sabharwal',
    price: '$44.15',
    publisher: 'Apress',
    year: 2015,
    pages: 272,
    language: 'English',
    format: 'Paper book / ebook (PDF)',
    isbn10: 123252,
    isbn13: 2331542,
    error: 0,
    url: 'we',
  },
  {
    id: 8,
    image: image1,
    rating: 5,
    desc: 'Practical Guide to MongoDB: Architecting, Developing, and Administering MongoDB begins with a short introduction to the basics of NoSQL databases and then introduces readers to MongoDB - the leading document based NoSQL database, acquainting them step-by-step with all aspects of MongoDB.Practical Gu...',
    subtitle:
      'Astronauts Kayla Barron and Raja Chari floated out of the International Space Station airlock for a spacewalk Tuesday, installing brackets and struts to support new solar arrays to upgrade the research lab’s power system on the same day that crewmate Mark Vande Hei marked his 341st day in orbit, a U.S. record for a single spaceflight.',
    title: 'Practical MongoDB',
    authors: 'Shakuntala Gupta Edward, Navin Sabharwal',
    price: '$44.15',
    publisher: 'Apress',
    year: 2015,
    pages: 272,
    language: 'English',
    format: 'Paper book / ebook (PDF)',
    isbn10: 123252,
    isbn13: 2331542,
    error: 0,
    url: 'we',
  },
  {
    id: 9,
    image: image1,
    rating: 2,
    desc: 'Practical Guide to MongoDB: Architecting, Developing, and Administering MongoDB begins with a short introduction to the basics of NoSQL databases and then introduces readers to MongoDB - the leading document based NoSQL database, acquainting them step-by-step with all aspects of MongoDB.Practical Gu...',
    subtitle:
      'Astronauts Kayla Barron and Raja Chari floated out of the International Space Station airlock for a spacewalk Tuesday, installing brackets and struts to support new solar arrays to upgrade the research lab’s power system on the same day that crewmate Mark Vande Hei marked his 341st day in orbit, a U.S. record for a single spaceflight.',
    title: 'Practical MongoDB',
    authors: 'Shakuntala Gupta Edward, Navin Sabharwal',
    price: '$44.15',
    publisher: 'Apress',
    year: 2015,
    pages: 272,
    language: 'English',
    format: 'Paper book / ebook (PDF)',
    isbn10: 123252,
    isbn13: 2331542,
    error: 0,
    url: 'we',
  },
  {
    id: 10,
    image: image1,
    rating: 3,
    desc: 'Practical Guide to MongoDB: Architecting, Developing, and Administering MongoDB begins with a short introduction to the basics of NoSQL databases and then introduces readers to MongoDB - the leading document based NoSQL database, acquainting them step-by-step with all aspects of MongoDB.Practical Gu...',
    subtitle:
      'Astronauts Kayla Barron and Raja Chari floated out of the International Space Station airlock for a spacewalk Tuesday, installing brackets and struts to support new solar arrays to upgrade the research lab’s power system on the same day that crewmate Mark Vande Hei marked his 341st day in orbit, a U.S. record for a single spaceflight.',
    title: 'Practical MongoDB',
    authors: 'Shakuntala Gupta Edward, Navin Sabharwal',
    price: '$44.15',
    publisher: 'Apress',
    year: 2015,
    pages: 272,
    language: 'English',
    format: 'Paper book / ebook (PDF)',
    isbn10: 123252,
    isbn13: 2331542,
    error: 0,
    url: 'we',
  },
  {
    id: 11,
    image: image1,
    rating: 1,
    desc: 'Practical Guide to MongoDB: Architecting, Developing, and Administering MongoDB begins with a short introduction to the basics of NoSQL databases and then introduces readers to MongoDB - the leading document based NoSQL database, acquainting them step-by-step with all aspects of MongoDB.Practical Gu...',
    subtitle:
      'Astronauts Kayla Barron and Raja Chari floated out of the International Space Station airlock for a spacewalk Tuesday, installing brackets and struts to support new solar arrays to upgrade the research lab’s power system on the same day that crewmate Mark Vande Hei marked his 341st day in orbit, a U.S. record for a single spaceflight.',
    title: 'Practical MongoDB',
    authors: 'Shakuntala Gupta Edward, Navin Sabharwal',
    price: '$44.15',
    publisher: 'Apress',
    year: 2015,
    pages: 272,
    language: 'English',
    format: 'Paper book / ebook (PDF)',
    isbn10: 123252,
    isbn13: 2331542,
    error: 0,
    url: 'we',
  },
];
